#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/tree
#
# IDENTIFICATION
#    src/backend/utils/tree/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/tree
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = shm_tree.o

include $(top_srcdir)/src/backend/common.mk
